version: '3.8'

services:
  frontend:
    build:
      context: ./DeliverySystem-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: delivery_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: